name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"


# Nice work adding the entrypoint.sh script.

# In entrypoint.sh, all we're doing is outputting a "Hello world" message using an environment variable called MY_NAME.

# Next, we'll define the action.yml file which contains the metadata for our action.

# action.yml
# All actions require a metadata file that uses YAML syntax. The data in the metadata file defines the inputs, outputs and main entrypoint for your action.